# These are supported funding model platforms

github: gusbemacbe
ko_fi : gusbemacbe
patreon: gusbemacbe
custom : https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=KGZ3HKN6QHVMN&item_name=Donate+Suru%2B%2B+Folders&currency_code=USD